### ISSUE TITLE
I am not getting url inspite of it I am getting null  This is my code snippet String url =await AwsS3.uploadFile(         accessKey: AKxxxxxxxxxxxxxxxxxxxxxxxxxxxx,         secretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,         destDir: "xyz",         filename: visitUuid + ".pdf",         file:file,                 bucket: "abc",         region:         "ap-southeast-1"           ).then((value) {         print(value);     }).catchError((onError){         print(onError);     });   Please help me out.

### ISSUE THREAD

**Issue by quran123** [Serdnad/aws_s3_upload#1]

**Comment by Serdnad** [comment]
Sorry, I'm only now seeing your issue! The library will return null in the case of an error - maybe this should be changed to a throw. Regardless, in that case it should also print the error, which would help me solve your issue.

If you've since fixed this or moved on, let me know so I can close this.

**Comment by quran123** [comment]
I fixed the issue on my end.You can close this

Thank you
Anushka Tayal

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aligurelli** [comment]
@quran123 how did you handle. I am still facing kinda similar error.
