### ISSUE TITLE
Uploading to S3 bucket

### ISSUE THREAD

**Issue by CameronGleichauf** [Serdnad/aws_s3_upload#5]
Is the: 

final endpoint = 'https://$bucket.s3-$region.amazonaws.com';

syntax still proper for s3 buckets? I am getting a "SocketException: Failed host lookup: {endpoint}" error when I try to upload a file to S3

**Comment by CameronGleichauf** [comment]
Believe the endpoint should be structured: 'https://s3.$region.amazonaws.com/$bucket' instead

**Comment by Serdnad** [comment]
Should be fixed by #11

**Comment by mwakaambrose** [comment]
@Serdnad Endpoint still doesn't work for me. Could you maybe expose the endpoint as an optional param?
